#' gaslight_prep
#'
#' Cleans and format input text, omit stopwords, lemmatize, splits to one word per row
#'
#' @name gaslight_prep
#' @param clean_dat a dataframe generated by the read_me() function
#' @return a dataframe one-word-per-row format with variables of interest appended
#' @importFrom dplyr select
#' @importFrom magrittr %>%
#' @importFrom textclean replace_contraction
#' @importFrom dplyr group_by
#' @importFrom tm stripWhitespace
#' @importFrom tm removeWords
#' @importFrom dplyr mutate
#' @importFrom stringr str_squish
#' @importFrom  tidyr separate_longer_delim
#' @importFrom dplyr left_join
#' @importFrom tidyr drop_na
#' @importFrom dplyr ungroup
#' @importFrom tidyr pivot_longer
#' @importFrom dplyr arrange
#' @export

gaslight_prep <- function(textData) {
  # x <- x %>% dplyr::select(ID, text)
  # x$ID <- as.factor(x$ID)
  # load("data/omissions_dyads23.rda") #run when in package
  # load("data/affvec_22dim.rda") #run when in package
  #load("data/gaslight_basevector.rda") #run when in package, loads base gaslighting vector
  gaslightBasevector$ID <- as.factor(gaslightBasevector$ID)
  # clean and transform data
  textData <- Lex2Emo::transformText(textData)

  textData <- textData %>%
    dplyr::select(ID, Dimension, Factor_Score)

  print(textData)
  print(gaslightBasevector)

  gasTestPrepped <- rbind(gaslightBasevector,textData)
  z$dimension <- factor(z$dimension, levels = c('belonging', 'envy', 'apprehension', 'compassion', 'pride', 'delight', 'doubt', 'woe', 'forgiveness', 'exuberance', 'euphoria', 'tranquility', 'indifference', 'powerlessness', 'shame', 'animosity', 'awe', 'surprised', 'fury', 'repugnance', 'agitation', 'exultation'))
  gasTestPrepped <- gasTestPrepped %>% dplyr::arrange(ID, dimension)
  return(gasTestPrepped)
}
