#' clean_me
#'
#' Cleans and format input text, omit stopwords, lemmatize, splits to one word per row
#'
#' @name prep_txt
#' @param clean_dat a dataframe generated by the read_me() function
#' @return a dataframe one-word-per-row format with variables of interest appended
#' @importFrom dplyr select
#' @importFrom magrittr %>%
#' @importFrom textclean replace_contraction
#' @importFrom dplyr group_by
#' @importFrom tm stripWhitespace
#' @importFrom tm removeWords
#' @importFrom dplyr mutate
#' @importFrom stringr str_squish
#' @importFrom textstem lemmatize_strings(x)
#' @importFrom  tidyr separate_longer_delim
#' @importFrom dplyr left_join
#' @importFrom tidyr drop_na
#' @importFrom dplyr ungroup
#' @importFrom tidyr summarise_if
#' @importFrom tidyr pivot_longer
#' @importFrom dplyr arrange
#' @export gas_test_prepped

prep_txt <- function(x) {
  x <- x %>% dplyr::select(ID, text)
  x$ID <- as.factor(x$ID)
  load("data/omissions_dyads23.rda") #run when in package
  load("data/affvec_22dim.rda") #run when in package
  load("data/gaslight_basevector.rda") #run when in package, loads base gaslighting vector
  gaslight_basevector$ID <- as.factor(gaslight_basevector$ID)
  y <- gaslight_basevector
  cleanme <- function(x){
    x <- tolower(x)
    x <- gsub("\"", " ", x)
    x <- gsub("\n", " ", x)
    x <- gsub("`", "'", x)  # replaces tick marks with apostrophe for contractions
    x <- textclean::replace_contraction(x) #replace contractions
    x <- gsub("-", " ", x)
    x <- gsub("[^a-zA-Z]", " ", x) #omit non-alphabetic characters
    x <- tm::stripWhitespace(x)
    x <- stringr::str_squish(x)
    x <- tm::removeWords(x, omissions_dyads23$word)
    x <- textstem::lemmatize_strings(x) #lemmatize
  }
  x <- x %>% mutate(cleaned_targettext = cleanme(text)) %>% select(!text)
  x <- x %>% tidyr::separate_longer_delim(cleaned_targettext, delim = " ")
  x <- dplyr::left_join(x, affvec_22dim, by = c("cleaned_targettext" = "word"))
  x <- tidyr::drop_na(x) #drop rows with missing values for word

#group and summarize each text
x <- x %>% dplyr::group_by(ID) %>% dplyr::summarise_if(is.numeric, mean, na.rm = TRUE) %>% ungroup()
x <- x %>% tidyr::pivot_longer(cols=c('belonging', 'envy', 'apprehension', 'compassion', 'pride', 'delight', 'doubt', 'woe', 'forgiveness', 'exuberance', 'euphoria', 'tranquility', 'indifference', 'powerlessness', 'shame', 'animosity', 'awe', 'surprised', 'fury', 'repugnance', 'agitation', 'exultation'), names_to="dimension", values_to="fac_score")
#reorder levels of factor in descending magnitude of factor score from base gaslighting vector
x$dimension <- as.factor(x$dimension)
x <- data.frame(x)
z <- rbind(y,x)
z$dimension <- factor(z$dimension, levels = c('belonging', 'envy', 'apprehension', 'compassion', 'pride', 'delight', 'doubt', 'woe', 'forgiveness', 'exuberance', 'euphoria', 'tranquility', 'indifference', 'powerlessness', 'shame', 'animosity', 'awe', 'surprised', 'fury', 'repugnance', 'agitation', 'exultation'))
z <- z %>% arrange(ID, dimension)
gas_test_prepped <- z
return(gas_test_prepped)
}
