#' gaslight_summarize
#'
#' Computes cosine distance from each input text to the base gaslighting vector
#'
#' @name gaslight_summarize
#' @param gaslight_prepped a dataframe generated by the gaslight_prep() function
#' @return a table of cosine distances one for every document
#' @importFrom dplyr select
#' @importFrom magrittr %>%
#' @importFrom dplyr group_by
#' @importFrom dplyr mutate
#' @importFrom dplyr ungroup
#' @importFrom tidyr summarize
#' @importFrom tidyr pivot_longer
#' @importFrom dplyr filter
#' @importFrom lsa cosine
#' @export gaslight_summarize

gaslight_summarize <- function(x) {
    #takes dataframe of 1 summary vector for each document (22 dimensions), compares cosine distance of each document to base vector, converts to z-score
    load("data/gaslight_basevector.rda")
    load("data/traindist.rda")
    basevec <- x %>% dplyr::filter(ID == "base_vector") %>% select(fac_score)
    z <- x %>% dplyr::group_by(ID) %>% dplyr::summarize(cosdist_value =   lsa::cosine(basevec$fac_score, fac_score)) %>% ungroup()
    m_train <- mean(traindist)
    sd_train <- sd((traindist))
    z <- z %>% mutate(z_doc = (cosdist_value-m_train)/sd_train)
    z <- z %>% mutate(GaslightZ_neg1 = ifelse(z_doc<=-1,'NO GASLIGHTING', "YES GASLIGHTING"))
    z <- z %>% mutate(GaslightZ_neg125 = ifelse(z_doc<=-1.25,'NO GASLIGHTING', "YES GASLIGHTING"))
    z <- z %>% mutate(GaslightZ_negpt5 = ifelse(z_doc<=-0.5,'NO GASLIGHTING', "YES GASLIGHTING"))
    z$GaslightZ_negpt5<- as.factor(z$GaslightZ_negpt5)
    z$GaslightZ_neg1 <- as.factor(z$GaslightZ_neg1)
    z$GaslightZ_neg125 <- as.factor(z$GaslightZ_neg125)
    return(z)
  }
